name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    name: "Push documentation"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: "Installing dependencies"
        run: |
          sudo apt-get install -y curl \
            pkg-config \
            findutils \
            wget \
            unzip doxygen  texlive-font-utils

          pip install mkdocs
          pip install mkdocs-gitbook
          wget https://github.com/matusnovak/doxybook2/releases/download/v1.3.6/doxybook2-linux-amd64-v1.3.6.zip
          unzip doxybook2-linux-amd64-v1.3.6.zip

      - name: Doxygen generation
        run: |
          doxygen doxygen.cfg
          ./bin/doxybook2 --input Doxygen/xml --config docs/.doxybook/config.json --output docs/src/Api

      - name: Building docs
        run: |
          cd docs/
          mkdocs build
          cd ../
          mv docs/site ./

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
